### ISSUE TITLE
Existing builds cause an immediate trigger when pipeline is unpaused for the first time

### ISSUE THREAD

**Issue by aullom1** [mcarey-solstice/concourse-job-resource#1]
Using concourse-job-resource as a get trigger will cause the trigger to fire immediately if the source build has any versions.

```yaml
resources:
- name: source-job-trigger
  type: concourse-pipeline
  source: ...

jobs:
- name: my-job
  plan:
  - get: source-job-trigger
    trigger: true
  ...
```

If there are any builds of `source-job-trigger`, then `my-job` will be triggered immediately.  It would be nice to be able to ignore builds older than a certain date, or to ignore all builds if the `version.start_time` is null/empty.
